### PR TITLE
Ticket 58 59

### PR DESCRIPTION
**Pull request by LibanBehi**
did error page/health-check-route in one ticket

### CODE REVIEW

**Review by TiciaD — APPROVED** [review]
Not sure why but it was showing another `ErrorPage.tsx` outside of `client/src` again, I went ahead and deleted it though so looks good now. Good job Liban!

**Comment by LibanBehi** [comment]
Yeah it’s weird but thank you!

**Review by riboney — APPROVED** [review]
I think the error page is supposed to be setup in react router so that its automatically displayed instead of the default:
image

Like this? (might be different for the new version of react-router)
image

Also `Error-page.tsx` should probably be placed in `pages` or components directory? And its file name does not seem to match normal fileNaming conventions...


Health check works. But there are eslint violations. Its not a big deal, but we should try to maintain some code quality standards

image


Nevertheless I'll approve the PR so that we have code contributions from everyone officially merged in. I guess we can always fix the issues in other tickets

**Comment by LibanBehi** [comment]
Gotcha . I’ve been looking at my new pr and I have some questions that are
confusing me.

**Comment by TiciaD** [comment]
> I think the error page is supposed to be setup in react router so that its automatically displayed instead of the default: image
> 
> Like this? (might be different for the new version of react-router) image
> 
> Also `Error-page.tsx` should probably be placed in `pages` or components directory? And its file name does not seem to match normal fileNaming conventions...
> 
> Health check works. But there are eslint violations. Its not a big deal, but we should try to maintain some code quality standards
> 
> image
> 
> Nevertheless I'll approve the PR so that we have code contributions from everyone officially merged in. I guess we can always fix the issues in other tickets

@riboney Yeah I figured we can make some adjustments in our next PR, especially since when he started this PR, the initial routing wasn't set up yet. If you want, I can pull this down and add those adjustments really quick so Liban can focus on his other tickets

**Comment by riboney** [comment]
> > I think the error page is supposed to be setup in react router so that its automatically displayed instead of the default: image
> > Like this? (might be different for the new version of react-router) image
> > Also `Error-page.tsx` should probably be placed in `pages` or components directory? And its file name does not seem to match normal fileNaming conventions...
> > Health check works. But there are eslint violations. Its not a big deal, but we should try to maintain some code quality standards
> > image
> > Nevertheless I'll approve the PR so that we have code contributions from everyone officially merged in. I guess we can always fix the issues in other tickets
> 
> @riboney Yeah I figured we can make some adjustments in our next PR, especially since when he started this PR, the initial routing wasn't set up yet. If you want, I can pull this down and add those adjustments really quick so Liban can focus on his other tickets

No issues here! Thank you

**Comment by TiciaD** [comment]
> > > I think the error page is supposed to be setup in react router so that its automatically displayed instead of the default: image
> > > Like this? (might be different for the new version of react-router) image
> > > Also `Error-page.tsx` should probably be placed in `pages` or components directory? And its file name does not seem to match normal fileNaming conventions...
> > > Health check works. But there are eslint violations. Its not a big deal, but we should try to maintain some code quality standards
> > > image
> > > Nevertheless I'll approve the PR so that we have code contributions from everyone officially merged in. I guess we can always fix the issues in other tickets
> > 
> > 
> > @riboney Yeah I figured we can make some adjustments in our next PR, especially since when he started this PR, the initial routing wasn't set up yet. If you want, I can pull this down and add those adjustments really quick so Liban can focus on his other tickets
> 
> No issues here! Thank you

Updated! It's good to merge @LibanBehi!

**Pull request merged**
