### PR TITLE
feat:create-prisma-schema

### PR DESCRIPTION
**Pull request by JoeNeedham**

### CODE REVIEW

**Review by RichardZhang01 — APPROVED** [review]
Good first pass at the models. I think we can expand contactInfo into more specific columns, and build off of these as we need more tables.

**Comment by riboney** [comment]
I had some errors when applying the schema changes

Am going to investigate, till then this PR should not be approved
image

**Comment by riboney** [comment]
> I had some errors when applying the schema changes
> 
> Am going to investigate image

Ok, was able to fix it

The issue was that i had some previous schema/ database contents that was interfering with the new schema posted here

I ran migrations and tested out the database by inserting into user and profile. And it seems to work fine:
image

Although, I am unclear on whether the schema matches the user story.

**Review by riboney — APPROVED** [review]
Works on my computer

**Pull request merged**
