### PR TITLE
user routes

### PR DESCRIPTION
**Pull request by RichardZhang01**
Set up basic user crud endpoints. Also install and implement swagger, and small change to user model (add password field).

### CODE REVIEW

**Review by JoeNeedham — APPROVED** [review]
I was able to test and try routes with swagger. Great code.

**Review by riboney — CHANGES_REQUESTED** [review]
Requesting fix for tests failing for user module:
image


Im not sure if this is on my end or if its the code

Am investigating.

**Comment by RichardZhang01** [comment]
Tests should now all pass. Thanks

**Review by riboney — APPROVED** [review]
Tests are working. App is working. Awesome job

**Pull request merged**
