### PR TITLE
Connect frontend with backend

### PR DESCRIPTION
**Pull request by riboney**
Literrally just copy pasted code from the [implement-auth](https://github.com/chingu-voyages/v41-bears-team-20/tree/implement-auth)

It doesn't work atm. I think it will take me 2 more days to get it done

---

Edit:

**HOW TO TEST**
- Setup:
  - clone pull request `git fetch origin refs/pull/83/head:pr-83`
  - switch to branch: `git checkout pr-83`
  - Run `npm i`
  - Run `cd server`
  - Run `npm run db:docker:up`
  - Run `docker ps` to confirm containers are running
  - Run `npx prisma migrate` or `npx prisma reset`
  - Run `npm run start:dev:`
  - Open new terminal instance
  - Run `cd server`
  - Run `npx prisma studio` --> opens up database viewer
  - Open new terminal instance
  - Run `cd client`
  - Run `npm run dev`
  - Navigate to `http://localhost:5173/account/register` in the browser

- Sign up for account
  - See if password policy violation displays an error message
  - Inspect console.log, network tab, and application> localstorage for confirmation of sign up
  - See if you were navigated to home page that displays "Hello <user id> " message
  - See if the navbar changed to display sign out button

- Sign out
  - See if navbar changes and you are navigated to home page that displays "Home page"
  
- Sign in
  - go to `http://localhost:5173/account/login`
  - login with recently created account credentials
  - Follow same steps as `sign up for account` 
  
**Demos**

_Signup_
image
image

### CODE REVIEW

**Review by TiciaD — APPROVED** [review]
This looks great risby thanks for doing all this integration work! There's few GitHub actions notes about use of `any` type and some unused variables left in but other than that it works so I'll go ahead and approve!

**Comment by TiciaD** [comment]
Looks like you've moved a few things around as far as schemas and models and stuff so we'll have to get together at some point so we can go over where everything goes, this'll cause some merge conflicts for my EditProfile ticket and I want to make sure I stay uniform with the different folders you've setup

**Comment by RichardZhang01** [comment]
Works on my end as well. However, when I initially loaded up the page, I was logged in already. Not sure why - had the log out button displaying, and I didn't have anything in localstorage. Password validation on the front end seems to be working fine. Can sign up and log in with the same account.

**Comment by riboney** [comment]
thanks for the feedback

I've addressed these concerns in discord

Will be making the required fixes in future PRs

**Pull request merged**
