### PR TITLE
Setup database config

### LINKED ISSUE #22: Setup Dockerfile
**__Task Description__**
Describe the task to be completed.

**__Technical Considerations__**
Look into Cloud Service for MySQL

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

### PR DESCRIPTION
**Pull request by riboney**
Closes #22 

**WHAT**
- Dockerize MySQL database for dev environment
- Setup prisma and connect it to database via `.env` file
- Setup `prisma` module in nest.js as DAO 
- Setup ConfigModule to handle environment variables (see: [docs](https://docs.nestjs.com/techniques/configuration))

**WHY**
- Connecting database to backend is required to persist data
- Dockerizing database gives developers easy option to setup the database
- Using Prisma ORM to handle database simplifies database deployment and interactions
- Handling environment variables with ConfigModule is recommended by the Nest.js docs

**HOW**
- See [wiki](https://github.com/chingu-voyages/v41-bears-team-20/wiki/Database) for basic setup and commands

**Demo of Adminer, a database viewer**

https://user-images.githubusercontent.com/14286113/195462167-31c5b28a-c7bf-425c-a7b4-7f735cadc871.mp4

### CODE REVIEW

**Review by TiciaD — CHANGES_REQUESTED** [review]
Looks like this is setup to merge to `main`, can you switch that to the `develop` branch instead? You may have to merge `develop` into your branch first since it's been updated with your last PR

**Comment by riboney** [comment]
> Looks like this is setup to merge to `main`, can you switch that to the `develop` branch instead? You may have to merge `develop` into your branch first since it's been updated with your last PR

thanks, i completely missed that

changed it now

**Review by TiciaD — APPROVED** [review]
Thanks for fixing that! Looks good and thanks for getting all this configuration out of the way, this should save us a lot of time next week!

**Comment by riboney** [comment]
Closing PR to refactor dockerfile to accept ports from ENV instead of it being hardcoded

**Pull request merged**
